# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
sphinx:
  configuration: docs/conf.py
  # disable this for more lenient docs builds
  fail_on_warning: false
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - requirements: docs/requirements.txt
